service: cm-technical-challenge-http-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
plugins:
  - serverless-offline
functions:
  reverser:
    handler: handler.reverser
    events:
      - httpApi:
          path: /
          method: get
